configMap:
  mountPath: /opt/{{ cookiecutter.app_name }}/params

app:
  {%- if cookiecutter.is_server != "y" %}
  enabled: false
  {%- else %}
  http:
    port: 8080

  istio:
    injected: true

  readiness:
    path: /healthz

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
{%- endif %}

{%- if cookiecutter.is_worker == "y" or cookiecutter.is_server != "y" %}

worker:
  enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
{%- endif %}

{%- if cookiecutter.use_migrate_migration == "y" %}

migration:
  enabled: true

  configMap: "{{ cookiecutter.app_name }}-app-dev"

  command:
    - {{ cookiecutter.app_name }}
    - migrate

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
{%- endif %}

{%- if cookiecutter.is_server != "y" %}

service:
  enable: false
{%- endif %}

ingress:
  enabled: false

virtualService:
{%- if cookiecutter.is_server != "y" or cookiecutter.connectivity == "private" %}
  enabled: false
{%- elif cookiecutter.is_server == "y" and cookiecutter.connectivity == "public" %}
  enabled: true

  gateways:
    - backend-gateway/backend-gateway

  hosts:
    - geni.ktbs.dev

  routes:
    - match:
        - uri:
            prefix: /{{ cookiecutter.app_name }}/
      retries:
        attempts: 3
        perTryTimeout: 2s
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ cookiecutter.app_name }}-app-dev
            port:
              number: 80
          weight: 100
{%- endif %}
