configMap:
  mountPath: /opt/{{ cookiecutter.app_name }}/bin/params

app:
  {%- if cookiecutter.is_server != "y" %}
  enabled: false
  {%- else %}
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
{%- endif %}

{%- if cookiecutter.is_worker == "y" or cookiecutter.is_server != "y" %}

worker:
  enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
{%- endif %}

{%- if cookiecutter.use_migrate_migration == "y" %}

migration:
  enabled: true

  configMap: "{{ cookiecutter.app_name }}-app-stg"

  command:
    - {{ cookiecutter.app_name }}
    - migrate

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
{%- endif %}

{%- if cookiecutter.is_server != "y" %}

service:
  enable: false
{%- endif %}

ingress:
{%- if cookiecutter.is_server != "y" or cookiecutter.connectivity == "private" %}
  enabled: false
{%- elif cookiecutter.is_server == "y" and cookiecutter.connectivity == "public" %}
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"

  tls:
    - hosts:
        - {{ cookiecutter.app_name }}.ktbs.xyz

  hosts:
    - host: {{ cookiecutter.app_name }}.ktbs.xyz
      path:
        - "/"
{%- endif %}
