auth:
    username: ENC[AES256_GCM,data:HJLZF/EjH9Kb,iv:xPXVWTzS3GySPin4N+yu/Q8td+0VXyDgh0RAOYkFIjc=,tag:zg0E259+jcfEAi3baza2vg==,type:str]
    password: ENC[AES256_GCM,data:k0EnnBQ9nuSQxe2etU3JkHjddbHn0fphBrS61zYTrlA=,iv:WfIFFnKCIBIBAzjkoGK08MU2kq3rBmp9kqhCdF2eyFY=,tag:8LpxkU+0Aj7FNDUeb4e3pA==,type:str]
    erlangCookie: ENC[AES256_GCM,data:d7bmT07w42WJCPH8JDevdD5DczuKDtkYSaUsTrc0pjE=,iv:R9RybVbRmx6eyqpZGf05CtEGLVd7L5qYhojc/KqAawc=,tag:QH0ZOCc9SzYv67pE5Dvz+w==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/kitabisa-stg/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-11-05T05:41:05Z'
        enc: CiQAS2FqNaQPhPl8+jFcQIbowfSqCOT+jHdQo+fzzbJKMoDgDXYSSQB/YcCYP35Vcg+PTNTTFqUbYhgs+PZWMaeULYvuhGgaPYYDrw+VmNC1qG4IsPW7h3lexsybvjNsqoibfneWT/aGe/qJ9vpPZa0=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-05T05:41:06Z'
    mac: ENC[AES256_GCM,data:y5IcoNYPnpaGk3CibfOAON2TJRMdeUPW4zgJa7pLl7eQqY6NpJYE2D5jsghZeIBx0siWUY6rxKfp+q56Uk6n+nLY/oUYl9Xc/dLaKg73k4+7BJhesV7ghtHZVZVt6cLnu5fgoT1HZL1yVZ00bCzYvYyO1NvVUuB1qcGB3Fo6opw=,iv:YpVEDebT18ZvJMLVBdRUu27WOfVnGS7ZpqebvqJiN2Y=,tag:nplRxx7I1VXGARtZ2zk4Kg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
