creation_rules:
  - path_regex: .infra/helm/dev/*
    gcp_kms: projects/flip-id-stg/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: .infra/helm/stg/*
    gcp_kms: projects/flip-id-stg/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: .infra/helm/uat/*
    gcp_kms: projects/flip-id-uat/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: .infra/helm/prod/*
    gcp_kms: projects/flip-id/locations/global/keyRings/sops/cryptoKeys/sops-key
