apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ cookiecutter.app_name }}-configmap
  namespace: frontend
data:
  config.yml: |
    database:
      driver: "mysql"
      name: "{{ cookiecutter.app_name }}"
      user: "$DB_USERNAME"
      password: "$DB_PASSWORD"
      host: "[host-name]"
      port: "6033"

    app:
      env: "staging"
      dbDebug: true
      apiPrefix: ""

    server:
      port: "9001"

    jwt:
      expirationTime: "648000"
      secret: "$JWT_SECRET"

    Sentry:
      DSN: "dsn-sentry"

    flipServer:
      baseUrl: "https://b2c-regression-box.flip.id/api"

    cache:
      isEnable: true
      host: "[cache-host]"
      port: 6379
      db: 1
      password:
      dialConnTimeOut: 5s
      readTimeOut: 5s
      writeTimeOut: 5s
      idleTimeOut: 10s
      maxConnLifeTime: 5m
      maxIdleConn: 2
      maxActiveConn: 50
      isWait: true

    errorMap:
        1001:
          id: "Error koneksi database"
          en: "Database connection error"
        1002:
          id: "Error koneksi cache"
          en: "Cache connection error"