secret:
    enabled: ENC[AES256_GCM,data:FpZY4g==,iv:9H6NiF6CGu4KHwK40RP9NyBNjvvASM+AsZB8bAp1mlI=,tag:CS71oVx1pxdImXJ8ceRA4A==,type:bool]
    data:
        APP_SECRET: ENC[AES256_GCM,data:RaNlRpRi,iv:UXtlqaw206g6HVE52yj97w8DgTIANMAiqvA/CC9fNt4=,tag:xjJzr4dfM1XlAPkxi8YiDg==,type:str]
        POSTGRE_USERNAME: ENC[AES256_GCM,data:nIUqNLEdzDJuT7eg2A==,iv:QCA5Hbu4W5MewjftBwaxLIOp7yx37aUIkVJy7m6Anic=,tag:f5uZPIm5Oz8wk0THA5LM+A==,type:str]
        POSTGRE_PASSWORD: ENC[AES256_GCM,data:1ApOaEvmcuTaLrGItQ==,iv:5e0FHX4dK5Cjbz5EghQF3e40H+PY/FYzSXCjAV8+bcQ=,tag:6wvdOGOszGUBnu0+r6/h3A==,type:str]
        MYSQL_USERNAME: ENC[AES256_GCM,data:08VHSgzqiQSWkib3jg==,iv:hm5LK78vYulSIWTelnB7AtjWWu7KyPYOgd32QpUuPvU=,tag:uWkKmQIYQWkIomuO5FK0xg==,type:str]
        MYSQL_PASSWORD: ENC[AES256_GCM,data:VHpdi+9oFhFaAH7l2w==,iv:85GH+t/67/96pCcgMdh1uWg9xCHR9nu0hiFmlSrU3tA=,tag:rM7nHZpx+9lW+m6FUmeQ+A==,type:str]
        CACHE_PASSWORD: ""
        INFLUX_USERNAME: ENC[AES256_GCM,data:V+YnKmryuHB26kr6oA==,iv:yxNI2Yebt1jFoo1Ya3pFlOYN7NfNliVV1QoEAukiz84=,tag:8c+cSb5OEvP6JwrjfDIgkg==,type:str]
        INFLUX_PASSWORD: ENC[AES256_GCM,data:0aOGr47PrMD3EhyeZg==,iv:bFYR/X86DtzVOnkVGa7X0Ru6bf9YXKP3VrbrI46TIiU=,tag:PzL7lt1NX2FywTBC3KuPPQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/kitabisa-dev/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2021-01-22T14:26:49Z'
        enc: CiQAWVpntujBOLbViFnNNWN+zlALpiriLeWuKNgdffeBE4dxS5sSSQB0IimzISrUQw3tW8Z3O7BoFvu8toYNppm5JZ7OGbh2DIAnFRf5xIGzZCAYoGtq6VTK8FBFSRXJkPWgdsmT7pYTge5D5DICzLI=
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-22T14:26:50Z'
    mac: ENC[AES256_GCM,data:OBiAbRxOIxX4SH/XJn3utJ70t6b/hNh9H1Xssc3saT2/yiiTk2AR3nZnEF0DRKWjANPeIh9wtkwCMHlYJ0Mv5Y2IUdlpd1PvT4DMW8upClL15Q8Wxg/FxcwItFxC6Hzy6/bS+Wg91kqje72aSfrs5RZD95CtVZ2JnU4ezJx2hVo=,iv:XMYwVZBSk6sepUCuER2ISJ6zlIyx94HwTL97KPIYohg=,tag:l6r/9MiS/t1+BZ5tI10eqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
