{% raw %}
repositories:
  - name: flip-id
    url: https://{{ requiredEnv "CHARTMUSEUM_HOST" }}
    username: {{ requiredEnv "CHARTMUSEUM_USER" }}
    password: {{ requiredEnv "CHARTMUSEUM_PASS" }}

  - name: bitnami
    url: https://charts.bitnami.com/bitnami
{% endraw %}

releases:
  {% raw %}
  - name: {{ requiredEnv "APP_NAME" }}-redis
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: data
      type: dependency
    chart: bitnami/redis
    version: 12.7.7
    values:
      - {{ requiredEnv "ENV" }}/redis.yaml

  - name: {{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: config
      type: main
    chart: flip-id/config
    version: ~0.4.0
    values:
      - {{ requiredEnv "ENV" }}/config.yaml
      - values.yaml.gotmpl
    secrets:
      - {{ requiredEnv "ENV" }}/secret.yaml
  {% endraw %}

  {% if cookiecutter.use_migrate_migration == "y" %}
  {% raw %}
  - name: {{ requiredEnv "APP_NAME" }}-migration-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: migration
      type: main
    chart: flip-id/migration
    version: ~0.4.0-alpha
    values:
      - {{ requiredEnv "ENV" }}/migration.yaml
      - values.yaml.gotmpl
  {% endraw %}
    needs:
      {% raw %}
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-redis
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
      {% endraw %}

  {% endif %}
  {% if cookiecutter.is_server == "y" %}
  {% raw %}
  - name: {{ requiredEnv "APP_NAME" }}-server-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: app
      type: main
    chart: flip-id/app
    version: ~0.17.0-alpha
    values:
      - {{ requiredEnv "ENV" }}/server.yaml
      - values.yaml.gotmpl
    hooks:
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args: ["label", "--overwrite", "namespaces", "{{ requiredEnv "APP_NAME" }}", "istio-injection=enabled"]
    needs:
    {% endraw %}
      {% raw %}
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-redis
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
      {% endraw %}
      {% if cookiecutter.use_migrate_migration == "y" %}{% raw %}
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-migration-{{ requiredEnv "ENV" }}
      {% endraw %}{% endif %}

  {% endif %}
  {% if cookiecutter.use_migrate_migration == "y" %}
  {% raw %}
  - name: {{ requiredEnv "APP_NAME" }}-worker-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: app
      type: main
    chart: flip-id/app
    version: ~0.17.0-alpha
    values:
      - {{ requiredEnv "ENV" }}/worker.yaml
      - values.yaml.gotmpl
    {% endraw %}
    needs:
      {% raw %}
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-redis
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
      {% endraw %}
      {% if cookiecutter.use_migrate_migration == "y" %}{% raw %}
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-migration-{{ requiredEnv "ENV" }}
      {% endraw %}{% endif %}

  {% endif %}
  {% raw %}
  - name: {{ requiredEnv "APP_NAME" }}-user-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: user
      type: main
    chart: flip-id/user
    version: ~0.3.0
    values:
      - {{ requiredEnv "ENV" }}/user.yaml
      - values.yaml.gotmpl

  - name: {{ requiredEnv "APP_NAME" }}-debugger
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: debugger
      type: optional
    chart: flip-id/debugger
    installed: {{ requiredEnv "ENV" | ne "prod" }}
  {% endraw %}
