version: 2.1

orbs:
  container: kitabisa/container@1.0.0

workflows:
  version: 2
  development:
    jobs:
      - container/gke-deploy:
          context: gke-dev
          filters:
            branches:
              only: /^dev.*/
  staging:
    jobs:
      - container/gke-deploy:
          context: gke-stg
          filters:
            branches:
              only: staging
  production:
    jobs:
      - container/gke-deploy:
          context: gke-prod
          filters:
            tags:
              only: /^v\d+.\d+.\d+.*/
            branches:
              ignore: /.*/
