{% raw -%}
secrets:
  envFrom:
    - "{{ .Values.meta.name }}-config-{{ .Values.meta.env }}"

configMaps:
  envFrom:
    - "{{ .Values.meta.name }}-config-{{ .Values.meta.env }}"
{%- endraw %}

migration:
  enabled: true

  command:
    - {{ cookiecutter.app_name }}
    - migrate

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
