secret:
    enabled: ENC[AES256_GCM,data:RJ1J4w==,iv:tWilLUAEqEpiGNpCaec5l5m9MVbU7H2rO7XIC6lzt+0=,tag:f4zMN3x8WFImVT07nOUcIw==,type:bool]
    data:
        APP_SECRET: ENC[AES256_GCM,data:VDZVBilh,iv:6ZstjNc6kFtvIeJL6GaNvt/36J/1q4ZRF0hBz3NFJZc=,tag:Ie2HkFuY1OuIAfE3g6QcGg==,type:str]
        POSTGRE_USERNAME: ENC[AES256_GCM,data:MNybRUSUOZv1l+DY5w==,iv:YntiQ4nSxQWQtPxNxWgNZypr3NQk35xKOL/FV0+zGpM=,tag:cBgcppz/U2cSBHbczecvMA==,type:str]
        POSTGRE_PASSWORD: ENC[AES256_GCM,data:N77j6ysbZk/mKefV0w==,iv:Sk3EV87lRLUFF48yrtk4JUqKmAy5U9u7SqE5mBVWDYk=,tag:6kCVPoCAA5EGWGmW6XAWWw==,type:str]
        MYSQL_USERNAME: ENC[AES256_GCM,data:qr6jUIGEMGP+XAwm4g==,iv:NX3D4kzPNTpLSsH8PCQEBGGdqpWEFL1BMSF2Rdf1S0w=,tag:vxBmPSbbcwBheglj1aYV3A==,type:str]
        MYSQL_PASSWORD: ENC[AES256_GCM,data:ywKIn8gmBagSM58pYw==,iv:BrzjUnz4iZA9DA657T6IIFkJWriAAUZPN5IVLcWyJLg=,tag:vuX1uDMm5ut8hU+sFVmQdQ==,type:str]
        CACHE_PASSWORD: ""
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/kitabisa-uat/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2021-01-25T14:25:13Z'
        enc: CiQAYuUNQmQbfIzxXMVBGibaVm5VL8dlNNmH8kPoT4xSlysxvWsSSQDm1bcZILSB17EwqjvN2IhVcnvSGfY88EfBpTgGl+ngJpx+pB1xvqoVnUZ4OZ5VzoBoKVZVSqQbBzypB4+kIoWZXHT0pdF49Lk=
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-25T14:25:13Z'
    mac: ENC[AES256_GCM,data:qeJb+lhWcQeY4JPulr9PgRMlIEIy+bhwSEYwrWkG6R6c15kJfqvevgH7y/37e3V+lpbGhLgyoNwsHTqba9tw3i5K8K4t51509cHbACo5PJKH8ClNJBlKP2phot4ZBi4mqyY7ZcoQllCZ9PeMX8FC8X9qxnUFY5K8YtDLI2xH3Fw=,iv:FXFBKCLV5sTyDmvdneUIaEQThZTwzJaJCOtHSoxQnwo=,tag:zfal1QkBeIVGflT/ZTLyng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
