{% raw -%}
secrets:
  envFrom:
    - "{{ .Values.meta.name }}-config-{{ .Values.meta.env }}"

configMaps:
  envFrom:
    - "{{ .Values.meta.name }}-config-{{ .Values.meta.env }}"
{%- endraw %}

server:
  enabled: true

  port: 8080

  istio:
    injected: true

  readiness:
    path: /health_check

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

{% if cookiecutter.connectivity == "public" -%}
service:
  enabled: true

ingress:
  enabled: true

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"

  tls:
    - hosts:
        - {{ cookiecutter.app_name }}.ktbs.us

  hosts:
    - host: {{ cookiecutter.app_name }}.ktbs.us
      paths:
        - "/"

virtualService:
  enabled: true

  gateways:
    - backend-gateway/backend-gateway

  hosts:
    - geni.ktbs.us

  routes:
    - match:
        - uri:
            prefix: /{{ cookiecutter.app_name }}/
      retries:
        attempts: 3
        perTryTimeout: 2s
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ cookiecutter.app_name }}-server-uat
            port:
              number: 80
          weight: 100
{%- else -%}
service:
  enabled: false

ingress:
  enabled: false

virtualService:
  enabled: false
{%- endif %}

autoscaling:
  minReplicas: 3
  maxReplicas: 20
